name: Nodejs
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  build:
    name: Nodejs
    # This job runs on Linux
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP: pohfy-nodejs-example
      IMAGE_NAME: pohfy123/nodejs-example
      IMAGE_TAG: latest
    steps:
      - uses: actions/checkout@v1

      - name: Docker build
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Test
        run: docker run --rm -i $IMAGE_NAME:$IMAGE_TAG yarn test

      - name: Docker login
        if: github.ref == 'refs/heads/master'
        uses: azure/container-actions/docker-login@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker push 
        if: github.ref == 'refs/heads/master'
        run: docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Docker logout
        if: github.ref == 'refs/heads/master' && always()
        uses: azure/container-actions/docker-logout@master

      - name: Heroku login
        if: github.ref == 'refs/heads/master'
        uses: "actions/heroku@master"
        with: 
          args: "container:login"
          secrets: |
            $HEROKU_API_KEY

      - name: Heroku push
        if: github.ref == 'refs/heads/master'
        uses: "actions/heroku@master"
        with: 
          args: "container:push -a $HEROKU_APP web"
          secrets: |
            $HEROKU_API_KEY

      - name: Heroku release
        if: github.ref == 'refs/heads/master'
        uses: "actions/heroku@master"
        with: 
          args: "container:release -a $HEROKU_APP web"
          secrets: |
            $HEROKU_API_KEY